### ISSUE TITLE
ability to preset issue/pr title and/or label in templates

### ISSUE THREAD

**Issue by tooomm** [isaacs/github#1252]
The [new option for several templates](https://blog.github.com/2018-05-02-issue-template-improvements/) is nice, it only lacks some more possibilities.

Like presetting a issue title with `[Bug]` or adding a `feature-request` label for example.
```
<!-- presettings
titel=[Bug]
label=feature-request,not-reviewed
--->
```
At best this would not be shown in the issue message, so that people can't simply adjust the label line and influence it like that.

**Comment by derekprior** [comment]
@tooomm you can set the `title`, `assignees`, and `labels` via YAML frontmatter (or via the online template editor, which will do that for you). For example:

```yaml
---
name: "Feature Request"
about: "Request a feature"
title: "Feature Reqeust: "
labels: "feature-request, not-reviewed"
assignees: "derekprior, tooomm"
---

Body of my template
```

When a user uses the template to create a new issue, the title, labels, and assignees will be preselected. Title can be overridden, just as body can today. Users with write access to the repo will be able to modify the label and assignee selections before submitting the issue if they wish. Users that do not have write access will not be able to change those because they do not have permissions.

Hope this helps!
