### ISSUE TITLE
Broken personal status update styles (low importance)

### ISSUE THREAD

**Issue by lunaroyster** [isaacs/github#1823]
I'm using Chrome. This is what I'm seeing

![Broken personal status update](https://i.imgur.com/wRJwTCZ.gif)

It's not particularly important.

**Comment by Lemmingh** [comment]
It seems that **GitHub fixed the problem today**.

---

The mention within the message was wrongly positioned and should be the cause.

I guess it's a mistake by GitHub; really don't understand why they set the following rules twice in <https://github.githubassets.com/assets/github-next-ff87f38bcca67ba9bba976476626ff56.css>:

```css
.user-status-container .team-mention,
.user-status-container .user-mention {
  white-space: normal;
}
```

Now a new rule has been appended to the [updated stylesheet](https://github.githubassets.com/assets/github-next-73c0f8498eedf23bf82030d683536ff9.css) 😂:

```css
.user-status-circle-badge-container .user-status-message-wrapper .team-mention,
.user-status-circle-badge-container .user-status-message-wrapper .user-mention {
  white-space: nowrap;
}
```

---

Actually, I tried to hack it and found a probably much simpler solution:

Remove those strange rules, and then add

```css
.no-wrap,
.no-wrap * {
  white-space: nowrap !important;
}
```

(Perhaps `!important` is not necessary.)
