### ISSUE TITLE
Automatically mirror an external repository by pulling at regular intervals (daily)

### ISSUE THREAD

**Issue by cirosantilli** [isaacs/github#415]
I want to take an arbitrary Git clone URL, give it to GitHub when creating a new repository, and have GitHub `git pull` the repository regularly, e.g. daily.

This would allow me to use GitHub's superior analysis features like contributor analysis and clean permalink URLs which other web interfaces do not have, so I can analyze projects which interest me but for which I do not control hooks.

Such repositories could even be "read only", such that the only update possible would be the daily pull, e.g. user pushes are forbidden. This way GitHub does not need to use so much storage.

On the upside for GitHub, you'd get more traffic by using good content from other projects.

Non-git imports like mercurial and SVN would be great as well.

I basically want to make the magic on request "mirrored on" feature of https://github.com/gcc-mirror/gcc available for anyone.

Related help pages:

- https://help.github.com/articles/about-github-mirrors/
- https://help.github.com/articles/duplicating-a-repository/

**Comment by andrewfenn** [comment]
I also want this feature but for different reasons:

* I want to be able to pull a HG repo on bitbucket at set time periods.
* I want to be able to still write to the repo so I can setup travis CI, etc.

By having this feature I can avoid HG and Bitbucket while still being able to follow up on open source project's upstream that still does use it.

**Comment by JAZ-013** [comment]
I wouldn't mind having this feature as well, but instead of at a specified interval (although that would be fine) it would be cool to have some sort of reverse webhook.  I develop locally using GitLab but push to GitHub to cater for a bunch of ~~picky~~ lovely users.  GitLab does webhooks so it would be nice to use that to tickle a project URL at Github to get it to pull my repository just like it did when I set it up initially,

**Comment by cirosantilli** [comment]
@JAZ-013 I agree that would be cool. Open a separate issue for it.

**Comment by JAZ-013** [comment]
No need.  I wrote a script that sits in the middle.  http://git.hazaarlabs.com/jamie/gitlab-sync

**Comment by TPS** [comment]
Or, alternatively, for all us "~~picky~~ lovely users," https://github.com/JAZ-013/gitlab-sync. 😜

**Comment by stuartpb** [comment]
Looping in [this Stack Overflow question](https://stackoverflow.com/questions/11370239/creating-an-official-github-mirror) about how GitHub used to do this, but no longer does.

**Comment by Akito13** [comment]
4 years and still open. Sad.

**Comment by fabiofdsantos** [comment]
+1

**Comment by imbsky** [comment]
+1

**Comment by hle-iad** [comment]
+1

**Comment by SamWhited** [comment]
Please don't +1, you're spamming others who follow this issue. Add an upvote using reactions. That said:

Can this be closed now that actions exist? Something like this should work after you import the repo if you put itin `.github/workflows/mirror.yml` or similar. Be sure to replace `$REPO` with the URL you want to clone:


```yaml
name: Mirror Repo
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror '$REPO'
        cd mux.git/
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git push --mirror github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

If you can't add files to the Repo in question, create a new repo that just contains GitHub actions for mirroring other repos and give it access to deploy keys for each repo it will mirror as secrets.
