### ISSUE TITLE
Selected text on repositories page is unreadable

### ISSUE THREAD

**Issue by aniketpant** [isaacs/github#63]
![screenshot from 2013-07-05 11 47 01](https://f.cloud.github.com/assets/777188/752219/943ec392-e53a-11e2-8284-a0fef0b2c124.png)

The above screenshot is taken on Ubuntu 12.04

I had mailed support a week earlier regarding this. They said that this is a Linux specific issue. Though I am not sure why that is the case because I see that it is happening due to this style:

``` css
.repolist .body {
  text-shadow: 0 0 5px #fff, 0 0 5px #fff, 0 0 5px #fff;
}
```
