### ISSUE TITLE
Feature Request: Line Lengths in Pull Requests

### ISSUE THREAD

**Issue by elsmorian** [isaacs/github#738]
I’m a Python dev, and line lengths can be pretty strict ( https://www.python.org/dev/peps/pep-0008/#maximum-line-length ) - it would be awesome to have a (toggle-able) line marker in Pull Requests to see lines that go over these guides - Maybe MVP it could just be a Col: ## label at the bottom of the screen showing the column the cursor is currently highlighted over?

**Comment by Mottie** [comment]
Are you referring to the PR commit changes message? If so, we have a [Stylish theme](https://userstyles.org/styles/107938/github-commit-limits) that adds a customizable background color showing text limits.

![](https://raw.githubusercontent.com/StylishThemes/GitHub-Commit-Limit/master/commit-limit.png)

**Comment by elsmorian** [comment]
@Mottie Aha! that isn't quite what I was after but a great solution!

I was wanting something similar, but for code line lengths in Pull Requests - I have in fact adapted your idea though into the following stylish css style which does roughly what I want!

```css
span.blob-code-inner {
   background: linear-gradient(to right, rgba(0, 0, 0, 0) 0, rgba(0,     0, 0, 0) 80ch, rgba(255, 157, 53, 0.5) 80ch) !important;
}
textarea[name='comment[body]'] { 
       background: linear-gradient(to right, rgba(0, 0, 0, 0) 0, rgba(0,     0, 0, 0) 80ch, rgba(255, 157, 53, 0.5) 80ch) !important;
}
```
