### ISSUE TITLE
Close pull request button position - can we make better

### ISSUE THREAD

**Issue by FirojAktarulIslam** [isaacs/github#873]
Once I by mistake  clicked 'Close pull request' button instead of Comment button while reviewing a pull request. Later I felt 'Close pull request' button should be little far away. 

![close_pull_request](https://cloud.githubusercontent.com/assets/19914574/22606471/02dd432e-ea22-11e6-9678-0df1321c1a0b.png)

**Comment by cirosantilli** [comment]
Recommendation to increase chances of success: make your title precise. E.g.: "Put close pull request button further from comment button"

**Comment by Mottie** [comment]
You can use [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) (or Stylish) to add some custom css to make the button more visible:

![2017-02-09 12_39_50- from bind to on by energynumbers pull request 1293 mottie_tablesorter](https://cloud.githubusercontent.com/assets/136959/22797699/e6e7a554-eec4-11e6-883d-864b7b980440.png)


```css
@-moz-document domain("github.com") {
  button[data-comment-text="Close and comment"] {
    background: #911 !important;
    border-color: #c00 !important;
    color: #ddd !important;
  }
  button[data-comment-text="Close and comment"]:hover {
    background: #a11 !important;
    border-color: #c00 !important;
  }
}
```
