### ISSUE TITLE
Width in repo/repo/branches/yours is too small for PR numbers larger than 100000

### ISSUE THREAD

**Issue by maximebedard** [isaacs/github#888]
When the PR # >= 100000, the width of the column is to small and the icon overflows.

![image](https://cloud.githubusercontent.com/assets/801405/23239597/3f4854fc-f936-11e6-817e-fe82fc7d5d8f.png)

fix:  

```css
.pr-details {
  width: 147px
}
```
